services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.0
    container_name: elasticsearch
    restart: unless-stopped
    ports:
      - "49200:9200"
      - "49300:9300"
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      ES_JAVA_OPTS: "-Xms256m -Xmx256m"
      TZ: "Asia/Seoul"
    healthcheck:
      test: "curl -f http://localhost:9200 || exit 1"

  logstash:
    image: docker.elastic.co/logstash/logstash:8.3.0
    container_name: logstash
    restart: unless-stopped
    ports:
      - "45044:5044"
      - "45000:5000/tcp"
      - "45000:5000/udp"
      - "49600:9600"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline/
    depends_on:
      - elasticsearch
    environment:
      TZ: "Asia/Seoul"
    healthcheck:
      test: "curl -f http://localhost:9600 || exit 1"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.3.0
    container_name: kibana
    restart: unless-stopped
    ports:
      - "45601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      TZ: "Asia/Seoul"
    depends_on:
      - elasticsearch
    healthcheck:
      test: "curl -f http://localhost:5601 || exit 1"

  prometheus:
    image: prom/prometheus:v2.48.1
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "49090:9090"
    environment:
      TZ: "Asia/Seoul"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "9090" ]

  grafana:
    image: grafana/grafana:9.5.15
    container_name: grafana
    restart: unless-stopped
    ports:
      - "45300:3000"
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
      - TZ="Asia/Seoul"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - prometheus
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "3000" ]
